name: CI

on:
  push:
  pull_request:
    branches: [ "master", "next", "develop" ]
    
env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  SPRING_DATASOURCE_URL: ${{ secrets.DATABASE_URL }}
  SPRING_DATASOURCE_DRIVERCLASSNAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: semantic release  
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18
          branches: |
            [
              "master",
              {
                  "name": "next",
                  "prerelease": true,
                  "channel": "beta"
              },
              {
                  "name": "develop",
                  "prerelease": true,
                  "channel": "alpha"
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
